config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "public_recipes#index"
  resources :users, only: [:index] do
    resources :recipes
    resources :inventories
  end
  resources :public_recipes, only: [:index, :show]

  get 'inventory_foods/:id/new', to: 'inventory_foods#new'
  delete 'inventory_foods/:id/destroy/:food_id', to: 'inventory_foods#destroy'
  post 'inventory_foods/:id/create', to: 'inventory_foods#create'
  resources :foods, only:[:index,:new,:create,:destroy]

  get 'recipe_foods/:id/new', to: 'recipe_foods#new'
  delete 'recipe_foods/:id/destroy/:food_id', to: 'recipe_foods#destroy'
  post 'recipe_foods/:id/create', to: 'recipe_foods#create'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all

    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Food
      can :read, Recipe, public: true
      can :manage, Recipe, user_id: user.id
      can :manage, Inventory, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_food, dependent: :destroy
  has_many :inventory_food, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }

  belongs_to :user, foreign_key: 'user_id'
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food, foreign_key: 'foods_id'
  belongs_to :inventory, foreign_key: 'inventory_id'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  belongs_to :user, foreign_key: 'user_id'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipes, foreign_key: 'user_id'
  has_many :inventories, foreign_key: 'user_id'

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(new_food_params)
    if @food.save
      redirect_to foods_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food.destroy
    redirect_to foods_path, notice: "#{@food.name} Food record successfully."
  end

  private

  def new_food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[show destroy]
  before_action :authenticate_user!, only: %i[new create destroy]
  def index
    @inventories = Inventory.all
  end

  def show
    @foods = @inventory.inventory_foods.includes(:food)
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(new_inventory_params)
    @inventory.user = current_user

    if @inventory.save
      flash[:notice] = 'Inventory created successfully!'
      redirect_to user_inventories_path
    else
      flash.now[:alert] = 'Something unexpected happened, inventory could not be created.'
      render :new
    end
  end

  def destroy
    if @inventory.destroy
      flash[:notice] = 'Inventory deleted successfully!'
    else
      flash[:alert] = 'Something unexpected happened, inventory could not be deleted.'
    end
    redirect_to user_inventories_path
  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def new_inventory_params
    params.require(:inventory).permit(:name)
  end
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  def new
    @inventory = Inventory.find(params[:id])
    @inventory_food = InventoryFood.new
  end

  def destroy
    @inventory_food = InventoryFood.find_by(id: params[:food_id])

    if @inventory_food.destroy
      flash[:notice] = 'Inventory food deleted successfully!!'
    else
      flash[:alert] = 'Something unexpected happened, inventory could not be deleted.'
    end
    redirect_to user_inventory_path(params[:id])
  end

  def create
    food_list = params[:inventory_food][:food_list]
    food_list = food_list.drop(1)
    food_list.each do |food|
      next unless InventoryFood.where(foods_id: food.to_i, inventory_id: params[:id]).blank?

      new_inventory_food = InventoryFood.new(foods_id: food.to_i, quantity: params[:inventory_food][:quantity],
                                             inventory_id: params[:id])
      new_inventory_food.save
    end
    redirect_to user_inventory_path(params[:id]), flash: { success: 'Inventory food has been added successfully!' }
  end

  def inventory_food_params
    params.require(:inventory_food).permit(:food_list, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:user).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.new
  end

  def destroy
    @recipe_food = RecipeFood.find_by(id: params[:food_id])

    if @recipe_food.destroy
      flash[:notice] = 'Recipe food deleted successfully!!'
    else
      flash[:alert] = 'Something unexpected happened, recipe could not be deleted.'
    end
    redirect_to user_recipe_path(params[:id])
  end

  def create
    food_list = params[:recipe_food][:food_list]
    food_list = food_list.drop(1)
    food_list.each do |food|
      next unless RecipeFood.where(food_id: food.to_i, recipe_id: params[:id]).blank?

      new_recipe_food = RecipeFood.new(food_id: food.to_i, quantity: params[:recipe_food][:quantity],
                                       recipe_id: params[:id])
      new_recipe_food.save
    end
    redirect_to user_recipe_path(params[:id]), flash: { success: 'Recipe food has been added successfully!' }
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_list, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show delete]
  before_action :authenticate_user!, only: %i[new create destroy]
  def index
    @recipes = Recipe.all
  end

  def new
    @user = User.find(params[:user_id])
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      redirect_to user_recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe.destroy

    redirect_to user_recipes_path
  end

  def show
    @foods = @recipe.recipe_foods.includes(:food)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/foods/index.html.erb
<section class="ps-5 pe-5">
<div class="bg-light d-flex flex-row-reverse">
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% count = 0 %>
    <% @foods.each  do |item| %>
        <tr>
        <th scope="row"><%= count = count + 1 %></th>
        <td><%= item.name %></td>
        <td><%= item.measurement_unit %></td>
        <td><b>$ </b><%= item.price %></td>
        </tr>
    <% end %>

    
  </tbody>
</table>
</section>

app/views/foods/new.html.erb
<div class="d-flex flex-column align-items-center">
  <h1>Add new food</h1>
  <%= form_with model: @food, url: foods_path,class: "d-flex flex-column", method: :post do |form| %>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <%= form.label :measurement_unit, 'Measurement unity' %>
    <%= form.text_field :measurement_unit %>
     <%= form.label :price, 'Price' %>
    <%= form.number_field :price %><br />
    <%= form.submit 'Add Food' %>
  <% end %>
</div>

app/views/inventories/index.html.erb
<% if @inventories.empty? %>
	<h2> Your list of inventories is empty! </h2>
	
<% else %>
	<h2> Your inventories list: </h2>
	
	<% @inventories.each do |inventory| %>
		<li class="d-flex flew-row">
			<h3 class="me-3"><%= link_to inventory.name, user_inventory_path(inventory.user_id, inventory) %></h3>
			<% if can? :destroy, inventory %>
			<%= button_to 'Delete', user_inventory_path(inventory.user_id, inventory), method: :delete, class: 'btn btn-danger' %>
			<% end %>
		</li>
	<% end %>
<% end %>
<%= link_to 'Add new inventory', new_user_inventory_path, class: 'btn btn-primary' %>

app/views/inventories/new.html.erb
<div>
    <h2> Create a new inventory: </h2>
    <%= form_with model: @inventory, url: user_inventories_path, method: :post do |form| %>
        <%= form.text_field :name %>
        <%= form.submit 'Add new inventory', class: 'btn btn-primary'%>
    <% end %>
</div>

app/views/inventories/show.html.erb
<h1><%= @inventory.name %></h1>
<% if can? :manage, @inventory %>
<%= link_to 'Add food',"/inventory_foods/#{@inventory.id}/new", class: 'btn btn-primary'%>
<% end %>

<div>
    <table class="table table-striped table-bordered w-100 mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= button_to 'Delete', "/inventory_foods/#{@inventory.id}/destroy/#{food.id}", method: :delete, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/inventory_foods/new.html.erb
<div class="container-fluid w-50 d-flex flex-column align-items-center">
  <h1 class="mb-5">Add food</h1>
  <%= form_with model: @inventory_food, url: "/inventory_foods/#{@inventory.id}/create", method: :post do |form| %>

    <p>Choose food from this list (press cntrl+click to select multiple)</p>

    <%= form.select :food_list, Food.order(:name).pluck(:name, :id), {}, {:multiple => true, required:true, class: "form-select mb-3"} %>
    <%= form.label :quantity, 'Quantity:', class: "form-label" %>
    <%= form.number_field :quantity, class: "form-control form-control-lg mb-4" %>
    <%= form.submit 'Add food', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%# javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
  <%= render partial: 'partials/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container">
    <% if user_signed_in? %>
    <a class="navbar-brand">Navbar</a>

<ul class="d-flex list-unstyled" style="--bs-scroll-height: 100px;">
  <li class="nav-item">
     <%= link_to "Foods", foods_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "New food", new_food_path, class: "nav-link" %>

  </li>
  <li class="nav-item">
   <%= link_to "Inventories", user_inventories_path(current_user), class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "Recipes", user_recipes_path(current_user), class: "nav-link" %>
   </li>

   <li class="nav-item">
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
  </li>
</ul>
<% end %>
</div>
</nav>

app/views/public_recipes/index.html.erb
<nav class="navbar navbar-light bg-light">
  <% unless user_signed_in? %>
      <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
  <% end %>
</nav>


<% if @public_recipes.empty? %>
	<h2> There are no public recipes! </h2>
	
<% else %>
<% @public_recipes.each do |recipe| %>
<% if recipe.public %>
    <div class="publicRecipesContainer">
        <div>
            <h2><%= link_to recipe.name, user_recipe_path(recipe.user_id, recipe) %></h2>
            <p>By <%= recipe.user.email %></p>
        </div>
        <p>Total food items:</p>
        <p>Total price:</p>
    </div>
      <% end %>
    <% end %>
<% end %>
<%= link_to "Go Home", users_path %>

app/views/recipe_foods/new.html.erb
<div class="container-fluid w-50 d-flex flex-column align-items-center">
    <h1 class="mb-5">Add food</h1>
    <%= form_with model: @recipe_food, url: "/recipe_foods/#{@recipe.id}/create", method: :post do |form| %>
  
      <p>Choose food from this list (press ctrl+click to select multiple)</p>
      
      <%= form.select :food_list, Food.order(:name).pluck(:name, :id), {}, {:multiple => true, required:true, class: "form-select mb-3"} %>
      <%= form.label :quantity, 'Quantity:', class: "form-label" %>
      <%= form.number_field :quantity, class: "form-control form-control-lg mb-4" %>
      <%= form.submit 'Add food', class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= link_to "Create new Recipe", new_user_recipe_path %>
<% @recipes.each do |recipe| %>
<ul class="recipeList">
    <li class="reciperecipe">
        <div>
            <h2><%= link_to recipe.name, user_recipe_path(recipe.user_id, recipe.id) %></h2>
            <% if can? :manage, recipe %>
            <%= button_to 'Destroy this post', { action: "destroy", id: recipe.id }, method: :delete, class: "btn btn-danger" %>
            <% end %>
        </div>
        <p><%= recipe.description %></p>
    </li>
</ul>
<% end %>

app/views/recipes/new.html.erb
<h1>New recipes</h1>

<%= form_with model: [@user, @user.recipes.build], method: :post do |form| %>
<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
</div>

<div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
</div>

<div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
</div>

<div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
</div>

<div>
    <%= form.label :public, style: "display: block" %>
    <%= form.text_field :public %>
</div>

<%= form.submit %>
<% end %>
<%= link_to "Go back", user_recipes_path %>

app/views/recipes/show.html.erb
<section>
    <h1><%= @recipe.name %></h1>
    <div class="showContainer">
    <div>
        <p><%= @recipe.preparation_time %></p>
        <p><%= @recipe.cooking_time %></p>
        <p>"Steps go here..."</p>
        <%= link_to "Generate shopping list", user_recipes_path %>
    </div>

    <div>
        <p>Public: <%= @recipe.public %></p>
        <% if can? :manage, @recipe %>
        <%= link_to 'Add ingredient', "/recipe_foods/#{@recipe.id}/new", class: 'btn btn-primary'%>
        <% end %>
    </div>
</div>

<div>
    <table class="table table-striped table-bordered w-100 mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= button_to 'Delete', "/recipe_foods/#{@recipe.id}/destroy/#{food.id}", method: :delete, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "All recipes", user_recipes_path, class: "btn btn-primary" %>

</section>

app/views/users/index.html.erb
<% if user_signed_in? %>
<%= button_to "log Out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
<% else %>
<%= link_to "log In", new_user_session_path, class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1>Users show</h1>